version: "3"
services:
  client:
      container_name: rv-client
      build:
        context: ./client
      volumes:
        - ./client:/app
        - /app/node_modules  
      ports:
        - "9000:9000"
  db:
    container_name: db
    image: mongo
    restart: always
    volumes:
          - db_data:/data/db
  # mongo-seed:
  #   build: ./mongo
  #   depends_on:
  #     - db  
  server:
    container_name: rv-server 
    build:
        context: ./server
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules    
    depends_on:
      - db  
    environment:  
      - MONGO_URL=mongodb://db:27017/revibed
      - APP_PORT=3000
    ports: 
      - "3000:3000"
volumes:
  db_data: {}      